/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EnergyBallsRouteImport } from './routes/energy-balls'
import { Route as HealthyBitesRouteImport } from './routes/healthy-bites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyBallsRoute = EnergyBallsRouteImport.update({
  id: '/energy-balls',
  path: '/energy-balls',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthyBitesRoute = HealthyBitesRouteImport.update({
  id: '/healthy-bites',
  path: '/healthy-bites',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/energy-balls': typeof EnergyBallsRoute
  '/healthy-bites': typeof HealthyBitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/energy-balls': typeof EnergyBallsRoute
  '/healthy-bites': typeof HealthyBitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/energy-balls': typeof EnergyBallsRoute
  '/healthy-bites': typeof HealthyBitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cookies' | '/energy-balls' | '/healthy-bites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookies' | '/energy-balls' | '/healthy-bites'
  id: '__root__' | '/' | '/cookies' | '/energy-balls' | '/healthy-bites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  EnergyBallsRoute: typeof EnergyBallsRoute
  HealthyBitesRoute: typeof HealthyBitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-balls': {
      id: '/energy-balls'
      path: '/energy-balls'
      fullPath: '/energy-balls'
      preLoaderRoute: typeof EnergyBallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthy-bites': {
      id: '/healthy-bites'
      path: '/healthy-bites'
      fullPath: '/healthy-bites'
      preLoaderRoute: typeof HealthyBitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  EnergyBallsRoute: EnergyBallsRoute,
  HealthyBitesRoute: HealthyBitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
