/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DessertsRouteImport } from './routes/desserts'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as EnergyBallsRouteImport } from './routes/energy-balls'
import { Route as HealthyBitesRouteImport } from './routes/healthy-bites'
import { Route as MainsRouteImport } from './routes/mains'
import { Route as StartersRouteImport } from './routes/starters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DessertsRoute = DessertsRouteImport.update({
  id: '/desserts',
  path: '/desserts',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyBallsRoute = EnergyBallsRouteImport.update({
  id: '/energy-balls',
  path: '/energy-balls',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthyBitesRoute = HealthyBitesRouteImport.update({
  id: '/healthy-bites',
  path: '/healthy-bites',
  getParentRoute: () => rootRouteImport,
} as any)
const MainsRoute = MainsRouteImport.update({
  id: '/mains',
  path: '/mains',
  getParentRoute: () => rootRouteImport,
} as any)
const StartersRoute = StartersRouteImport.update({
  id: '/starters',
  path: '/starters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/desserts': typeof DessertsRoute
  '/drinks': typeof DrinksRoute
  '/energy-balls': typeof EnergyBallsRoute
  '/healthy-bites': typeof HealthyBitesRoute
  '/mains': typeof MainsRoute
  '/starters': typeof StartersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/desserts': typeof DessertsRoute
  '/drinks': typeof DrinksRoute
  '/energy-balls': typeof EnergyBallsRoute
  '/healthy-bites': typeof HealthyBitesRoute
  '/mains': typeof MainsRoute
  '/starters': typeof StartersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/desserts': typeof DessertsRoute
  '/drinks': typeof DrinksRoute
  '/energy-balls': typeof EnergyBallsRoute
  '/healthy-bites': typeof HealthyBitesRoute
  '/mains': typeof MainsRoute
  '/starters': typeof StartersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/desserts'
    | '/drinks'
    | '/energy-balls'
    | '/healthy-bites'
    | '/mains'
    | '/starters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/desserts'
    | '/drinks'
    | '/energy-balls'
    | '/healthy-bites'
    | '/mains'
    | '/starters'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/desserts'
    | '/drinks'
    | '/energy-balls'
    | '/healthy-bites'
    | '/mains'
    | '/starters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  DessertsRoute: typeof DessertsRoute
  DrinksRoute: typeof DrinksRoute
  EnergyBallsRoute: typeof EnergyBallsRoute
  HealthyBitesRoute: typeof HealthyBitesRoute
  MainsRoute: typeof MainsRoute
  StartersRoute: typeof StartersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desserts': {
      id: '/desserts'
      path: '/desserts'
      fullPath: '/desserts'
      preLoaderRoute: typeof DessertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-balls': {
      id: '/energy-balls'
      path: '/energy-balls'
      fullPath: '/energy-balls'
      preLoaderRoute: typeof EnergyBallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthy-bites': {
      id: '/healthy-bites'
      path: '/healthy-bites'
      fullPath: '/healthy-bites'
      preLoaderRoute: typeof HealthyBitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mains': {
      id: '/mains'
      path: '/mains'
      fullPath: '/mains'
      preLoaderRoute: typeof MainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starters': {
      id: '/starters'
      path: '/starters'
      fullPath: '/starters'
      preLoaderRoute: typeof StartersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  DessertsRoute: DessertsRoute,
  DrinksRoute: DrinksRoute,
  EnergyBallsRoute: EnergyBallsRoute,
  HealthyBitesRoute: HealthyBitesRoute,
  MainsRoute: MainsRoute,
  StartersRoute: StartersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
